language: ruby
rvm: 1.9.3
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq kwalify
# install:
#   - gem install kwalify
script:
  ## Quick user data check.
  - kwalify -f metadata/users.schema.yaml metadata/users.yaml
