language: ruby
rvm: "1.9.3"
# before_install:
#   - sudo apt-get update -qq
#   - sudo apt-get install -qq kwalify
## Possible other way.
install:
  - gem install kwalify
script:
  ## Quick user data check.
  - kwalify -E -m metadata/users.schema.yaml | grep INVALID; test $? -ne 0
  - kwalify -E -f metadata/users.schema.yaml metadata/users.yaml | grep INVALID; test $? -ne 0
  - kwalify -E -m metadata/db-xrefs.schema.yaml | grep INVALID; test $? -ne 0
  - kwalify -E -f metadata/db-xrefs.schema.yaml metadata/db-xrefs.yaml | grep INVALID; test $? -ne 0
notifications:
  email:
    - sjcarbon@lbl.gov
    - cjmungall@lbl.gov
    - hdietze@lbl.gov
